
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Models
{

using System;
    using System.Collections.Generic;
    
public partial class ctphieuxuat
{

    public string maso { get; set; }
        [System.ComponentModel.DisplayName("Mã Sách")]
        public string masach { get; set; }
        [System.ComponentModel.DisplayName("Số lượng")]
        public int soluong { get; set; }
        [System.ComponentModel.DisplayName("Giá")]
        public int gia { get; set; }
        [System.ComponentModel.DisplayName("Thành tiền")]
        public int thanhtien { get; set; }

    public string maphieunhap { get; set; }
        [System.ComponentModel.DisplayName("Còn Nợ")]
        public Nullable<int> tienno { get; set; }



    public virtual phieuxuat phieuxuat { get; set; }

    public virtual sach sach { get; set; }

    public virtual phieunhap phieunhap { get; set; }

}

}
