//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdondl
    {
        public string maso { get; set; }
        public string madl { get; set; }
        public System.DateTime ngay { get; set; }
        public int sotien { get; set; }
    
        public virtual daily daily { get; set; }
    }
}
