//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuxuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieuxuat()
        {
            this.ctphieuxuats = new HashSet<ctphieuxuat>();
        }
    
        public string maso { get; set; }
        public string madl { get; set; }
        public string nguoinhan { get; set; }
        public System.DateTime tgian { get; set; }
        public int tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctphieuxuat> ctphieuxuats { get; set; }
        public virtual daily daily { get; set; }
    }
}
